### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by dcmeglio** [Techzune/petsafe-smartfeed#1]
It would seem Petsafe revamped their api and broke this library.

**Comment by Zeunas** [comment]
I have extracted the information from this project to create some sensors / switches in NodeRed / Home assistant. They were working fine until very recently, payload is now saying "Your account has been throttled due to excessive API usage. Please contact PetSafe customer care at https://www.petsafe.net/support/contact-us"...Wonder if it's related.

Trying to send a CURL command via any Run Curl commands online website, still works...however I'm quite noob to understand the reason why...

**Comment by dcmeglio** [comment]
They appear to have disabled the api and built a brand new on. This library will need to be updated.

**Comment by Techzune** [comment]
Hey all,
It looks like PetSafe has a limit on their API where it only supports one request per 5 minutes. Requesting data more often than that will cause the system to lock your account. For more info: https://community.hubitat.com/t/release-petsafe-smart-feeder-integration/44268?page=3

I am considering adding a check in this API to warn against requesting too often.
